#!/usr/bin/python
import socket, threading, thread, select, signal, sys, time, getopt
# ==========================================
# CONFIGURATION - AJI SYSTEM TLS
# ==========================================
LISTEN_ADDR = '0.0.0.0'
LISTEN_PORT = 443
TARGET_HOST = '127.0.0.1'
TARGET_PORT = 109  # Diarahkan ke Dropbear
RESPONSE = b'HTTP/1.1 101 <font color="green">Mantap TLS Switching Protocols</font>\r\n\r\n'
BUFFER_SIZE = 8192

class ProxyTLS:
    def __init__(self, listen_addr, listen_port):
        self.listen_addr = listen_addr
        self.listen_port = listen_port
        self.server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

    def forward(self, source, destination):
        try:
            while True:
                read, _, error = select.select([source, destination], [], [source, destination], 60)
                if error:
                    break
                for sock in read:
                    data = sock.recv(BUFFER_SIZE)
                    if not data:
                        return
                    if sock is source:
                        destination.sendall(data)
                    else:
                        source.sendall(data)
        except:
            pass
        finally:
            source.close()
            destination.close()

    def handler(self, client_soc):
        try:
            client_soc.recv(BUFFER_SIZE)
            target_soc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            target_soc.connect((TARGET_HOST, TARGET_PORT))
            client_soc.sendall(RESPONSE)
            self.forward(client_soc, target_soc)
        except:
            client_soc.close()

    def start(self):
        try:
            self.server.bind((self.listen_addr, self.listen_port))
            self.server.listen(100)
            while True:
                client, addr = self.server.accept()
                threading.Thread(target=self.handler, args=(client,), daemon=True).start()
        except Exception as e:
            sys.exit(1)

if __name__ == '__main__':
    proxy = ProxyTLS(LISTEN_ADDR, LISTEN_PORT)
    proxy.start()
END

chmod +x /usr/local/bin/ws-tls
systemctl restart ws-tls
